### ISSUE TITLE
Glimmer syntax: add a custom scope for component args !

### ISSUE THREAD

**Issue by flashios09** [lifeart/vsc-ember-syntax#17]
Hi Alex,

For now, the html attributes and component args are using the same scope `entity.other.attribute-name.handlebars`, so same color(style) for both html attributes and component args:

![image](https://user-images.githubusercontent.com/1313482/141144508-3f83b1f8-b071-4df3-aac7-4a0bc40de4ec.png)

For readability purpose, i think it's better to have a specific scope for components args, IDK maybe something like this `entity.other.glimmer-arg-name.handlebars`, then we can just specify a custom style for this scope.

Vscode `settings.json` file:
```json
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "text.html.handlebars meta.tag.any.handlebars entity.other.glimmer-arg-name.handlebars",
                "settings": {
                    "foreground": "#3bbe8f",
                    "fontStyle": "italic"
                }
            }
        ]
    },
    ...
}
```
![image](https://user-images.githubusercontent.com/1313482/141150413-c5420c39-e55c-462b-a5d6-898fa85052b5.png)

I can create a PR for :)

Thanks

**Comment by lifeart** [comment]
Hi @flashios09, thank you for feedback! I think it could be "entity.other.argument.name.handlebars", but I want to keep existing (default) higligting as-is out of the box, 

I have consern, that `@` is quite "visible" argument indicator, and having different colors for arguments and attributes introduce more visual noize. 

But, I'm completely open to any PR if we will be able to keep existing higlighting as-is and also customize it in way you mentioned.

Also, I like idea about way to "redefine" colors, and will be thankful to get PR to readme with this possibilities.

Let me know if we could figure out solution here

**Comment by lifeart** [comment]
Hi @flashios09! Sorry for delay, I figured out how to support this change without regression in vscode.
PR merged https://github.com/lifeart/vsc-ember-syntax/pull/18

**Comment by lifeart** [comment]
v1.0.7 available!
