### ISSUE TITLE
Highlighting helpers & s expressions breaks when moved on different lines

### ISSUE THREAD

**Issue by samselikoff** [lifeart/vsc-ember-syntax#2]
Latest prettier did some wonky things to my `{{yield hash()}}` helper, but I noticed it also breaks vsc-ember-syntax highlighting:

![image](https://user-images.githubusercontent.com/2922250/82479082-e58e3080-9a9f-11ea-9f97-48400589881c.png)

Here's the snippet:

```hbs
{{#if @isOpen}}
  <div class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg">
    <div class="rounded-md bg-white shadow-xs py-1">
      {{
        yield
        (hash
          Header=(component "dropdown/menu/header")
          Divider=(component "dropdown/menu/divider")
          Button=(component "dropdown/menu/button" closeMenu=@closeMenu)
          Link=(component "dropdown/menu/button" closeMenu=@closeMenu)
        )
      }}
    </div>
  </div>
{{/if}}
```

**Comment by lifeart** [comment]
@rjschie do you have capacity to take a look?

**Comment by rjschie** [comment]
Would we want to support this? In VSCode, the default HTML syntax highlighter doesn't account for this with the following (though Github syntax highlighting appears to). I guess it wouldn't hurt to add it in, but it seems outside the standard use-case, especially given that I think that prettier HBS formatting is not expected output (ref: [Prettier Glimmer Quest](https://github.com/jgwhite/prettier/issues/1)).

```html
<html>
  <head>
    <
      meta
      charset="utf-8"
    >
  </head>
</html>
```

**Comment by dcyriller** [comment]
This issue might be fixed by https://github.com/prettier/prettier/pull/10586

**Comment by lifeart** [comment]
Thank you @dcyriller!
