### ISSUE TITLE
Text / String escaping in gts / gjs appears broken?

### ISSUE THREAD

**Issue by NullVoxPopuli** [lifeart/vsc-ember-syntax#24]
I'm using 
 - https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-glimmer-syntax
 - with https://marketplace.visualstudio.com/items?itemName=chiragpat.vscode-glimmer
 
(because this vsc-ember-syntax plugin adds to vscode-glimmer, and I like lots of differentiation in code)

Discord context: https://discord.com/channels/480462759797063690/814921339219476571/970333665185906698

With just chiragpat's plugin:
![image](https://user-images.githubusercontent.com/199018/166151427-2b6f294f-964d-4d3b-859f-b16439090d03.png)

With both plugins:
![image](https://user-images.githubusercontent.com/199018/166151437-34acda9b-0b8b-45bb-980f-917452c49a3f.png)
![image](https://user-images.githubusercontent.com/199018/166151444-8ae6bf44-ed94-48ce-b324-0cfa019bd8a4.png)

Note how the text nodes in the template have more color than they should? and certain keywords / etc in the attribute value (string) have too many colors?

**Comment by NullVoxPopuli** [comment]
the component:

```gts
import Component from '@glimmer/component';
import { on } from '@ember/modifier';
import { action } from '@ember/object';

import { toBlob, toPng } from 'html-to-image';

import Menu from './menu';

/**
 * This component is injected via the markdown rendering
 */
export default class CopyMenu extends Component {
  @action
  copyAsText(event: Event) {
    let code = getSnippetElement(event);

    navigator.clipboard.writeText(code.innerText);
  }

  @action
  async copyAsImage(event: Event) {
    let code = getSnippetElement(event);

    await withExtraStyles(code, () => toClipboard(code));
  }

  <template>
    <Menu class="absolute top-3 right-4 z-10" data-test-copy-menu>
      <:trigger>
        📋
      </:trigger>
    

      <:options as |Item|>
        <Item {{on 'click' this.copyAsText}}>
          Copy as text
        </Item>
        <Item {{on 'click' this.copyAsImage}}>
          Copy as image
        </Item>
      </:options>
    </Menu>
  </template>
}
```

**Comment by NullVoxPopuli** [comment]
the other component:

``gts
import HeadlessMenu from 'ember-headlessui/components/menu';
import { PopperJS } from 'ember-popperjs';
import templateOnlyComponent from '@ember/component/template-only';

const Button = <template>
  <@item as |item|>
    <item.Element
      @tagName="button"
      class="
        bg-transparent
        block w-full select-none py-2 px-4 text-left
        text-black hover:bg-gray-100 focus:ring-4 ring-inset focus:outline-none
      "
      tabindex="0"
      data-test-menu-button
      ...attributes
    >
      {{yield}}
    </item.Element>
  </@item>
</template>;

<template>
  <HeadlessMenu as |menu|>
    <PopperJS as |trigger popover|>
      <menu.Button
        {{trigger}}
        class="
          text-black
          rounded-sm border border-gray-900 bg-white px-2 py-1 -my-1 text-left
          transition ease-in-out duration-150 sm:text-sm
          focus:ring-4 focus-visible:outline-none ring-ember-brand focus:outline-none
        "
        ...attributes
      >
        {{yield menu to="trigger"}}
      </menu.Button>
      <menu.Items
        {{popover}}
        class="absolute top-2 z-20 grid mt-1 rounded-sm bg-white shadow-lg min-w-max"
        data-test-menu-items
        as |items|
      >
        {{yield (component Button item=items.Item) to="options"}}
      </menu.Items>
    </PopperJS>
  </HeadlessMenu>
</template>
```

**Comment by lifeart** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/1360552/166151726-78d86460-946f-46c1-8e58-f5eeb169e1e4.png">

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/1360552/166151747-9a6f063d-7fb5-4a5f-a36b-7558eb3ba034.png">


<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1360552/166151763-70e3c4bf-86a2-4c13-b00d-53a8c2e50a35.png">


@NullVoxPopuli all looks fine for me.
(I use Dark+ theme)

**Comment by NullVoxPopuli** [comment]
> all looks fine

_red everywhere_ :sweat_smile: 

uhm, do you have both plugins installed?

**Comment by lifeart** [comment]
@NullVoxPopuli nope, only one (mine)
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1360552/166152337-897f21a3-3153-4721-afae-d31455c92f37.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/1360552/166152343-5af5c4a5-f1e3-4a41-acf2-ea548377a932.png">
