### ISSUE TITLE
Error message: There is no formatter for "glimmer-js" files installed

### ISSUE THREAD

**Issue by nolosb** [lifeart/vsc-ember-syntax#47]
When I try to format a .gjs file I get this error:
![image](https://github.com/lifeart/vsc-ember-syntax/assets/26887899/0a563594-fb44-4525-a437-5981dbeb99b9)

I added the extension manually to settings with `"prettier.documentSelectors": ["**/*.gjs"]`. Prettier tries to format the document then, but results in an error:

`Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.`

I tried configuring a parser in prettier config file like this:

```
 "overrides": [
    {
      "files": "*.gjs",
      "options": {
        "parser": "glimmer"
      }
    }
  ]
```

But get the same error. Not sure which parser to put here or if that is the wrong approach altogether? Thanks

**Comment by lifeart** [comment]
Hi @nolosb, thank you for report!
Could you check prettier version? 
We had autoconfiguration for it, merged here: https://github.com/lifeart/vsc-ember-syntax/pull/39
cc @evoactivity

**Comment by evoactivity** [comment]
@lifeart the prettier PR in this repo was to keep package.json formatted after the version increase from the ci workflow.

@nolosb Are you using in conjunction with prettier https://github.com/gitKrystan/prettier-plugin-ember-template-tag, it's needed for GJS/GTS

**Comment by nolosb** [comment]
@evoactivity ah ok, with the plugin it works! Thank you :)

In any case, wouldn't it be helpful to add this to the documention? I installed [ Ember.js Extension Pack](https://github.com/ember-tooling/vscode-ember-pack), but there's no mention on the Readme. Nor here on this one.

**Comment by evoactivity** [comment]
It's the first step in the ember-template-imports readme 😅 
https://github.com/ember-template-imports/ember-template-imports

But it could be useful to mention in the extension pack, I'll add it there asap.
