### ISSUE TITLE
Should we revert eslint settings back to global scope?

### ISSUE THREAD

**Issue by evoactivity** [lifeart/vsc-ember-syntax#54]
I commented this [here](https://github.com/lifeart/vsc-ember-syntax/pull/51#issuecomment-1867633297) but it's a closed PR so you might not have seen it.

I'm not convinced changing to the workspace scope was the right move, every project I open in vscode now automatically adds a `.vscode/settings.json` file with the eslint glimmer-js and glimmer-ts regardless what type of project it is. If you agree that is undesirable I'll create a PR that sets it back to global.

**Comment by lifeart** [comment]
@evoactivity yep, agree
