### ISSUE TITLE
underscore breaks highlight of js identifiers in template tag

### ISSUE THREAD

**Issue by void-mAlex** [lifeart/vsc-ember-syntax#58]
`_` is valid in a js identifier and should be recognised as such

```gjs
const Hello_worRlD123 = <template>hi</template>;
const HelloWorRlD123 = <template>hi</template>;

<template>
  <Hello_worRlD123 />
  <HelloWorRlD123 />
</template>
```
and vs code highlight of gjs file

![image](https://github.com/lifeart/vsc-ember-syntax/assets/5174947/b8441001-0a4d-44b7-bd06-3cef7f156b2f)

possibly issue with regex around here 
https://github.com/lifeart/vsc-ember-syntax/blob/7682c638e27c8f68471ee178838171b07e2468d7/syntaxes/src/text.html.ember-handlebars.mjs#L958

**Comment by evoactivity** [comment]
I think I'll add it to the `entity.name.type` as you suggested in discord, that should keep the colouring as you'd expect.
