### ISSUE TITLE
Improve md support

### ISSUE THREAD

**Issue by lifeart** [lifeart/vsc-ember-syntax#64]
I see some color drift in template for this snippet:

<img width="574" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/1360552/f618a604-0acf-4d47-96a7-921660716b04">

```gjs
export class Row extends Component<RowArgs> {
  <template>
    <tr class={{this.className}}>
      <td class="col-md-1">
        <a {{on "click" this.onClickRemove}}>
          <RemoveIcon />
        </a>
      </td>
    </tr>
  </template>
}
```

Looks like at some point `{` breaking flow.

**Comment by IgnaceMaes** [comment]
It should use `gts` instead of `gjs`, considering the code is using generics?

Although there does still seem to be something wrong with that too:

<img width="360" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/10243652/ccecf5bd-7f70-4ef6-816b-110f6e6ea40e">

**Comment by lifeart** [comment]
Yep, can confirm, gts/gjs case has some color drift.

<img width="533" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/1360552/8f6c02b6-2d6d-4104-b9e4-1ba32f12c977">

<img width="354" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/1360552/b6fd1272-0c4c-4666-9593-74a10c9d96bd">

**Comment by evoactivity** [comment]
I've been playing with this. None of the specific glimmer scopes are being applied. Not sure why yet.

Compare the scopes in a gts file
<img width="536" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/25cb305f-8615-4856-9256-53e0b158ebe4">

And in a markdown file
<img width="510" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/a252dfa4-961a-496d-b718-9fad51821c2a">

**Comment by evoactivity** [comment]
I'm trying to recreate the example @IgnaceMaes showed in his PR but I'm getting something completely different.

<img width="465" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/d7ca13fe-8340-43bc-a790-4a346a38a36d">

It's being highlighted as JSX.

**Comment by evoactivity** [comment]
I think I have a fix

<img width="618" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/6ccc4169-5ec1-40de-b7a8-22833ddf9f20">


I think using this in the repository

```json
"typescript": {
  "name": "source.ts",
  "begin": "(.*)",
  "while": "^(?!\\s*(<)(template)\\s*(>))",
  "patterns": [
    {
      "include": "source.ts"
    }
  ]
},
```

and setting the pattern to 
```json
{
  "include": "#main"
},
{
  "include": "#typescript"
}
```

will fix things, not sure if it'll introduce other errors or mess with other integrations though. Will need to do more testing.

**Comment by evoactivity** [comment]
That doesn't work in shiki or novalightshow :(

**Comment by evoactivity** [comment]
@lifeart is happens with the class brackets too, position doesn't matter unfortunately :(

**Comment by evoactivity** [comment]
I should have tried this first 😅  it doesn't colorize the bracket pairs in markdown typescript at all

<img width="353" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/5904317d-ff4e-473a-aeda-7445d308ef7c">

**Comment by evoactivity** [comment]
Unfortunately I found more issues with this approach, only when used in markdown though 😡

If `<template>` is assigned to a variable it breaks.

<img width="515" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/ab0d352d-b6fd-4418-aae7-d454e0d23cbb">

<img width="369" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/e6c0d2a6-899a-4ee5-8d73-1ecbfc504f33">


I can get the same problem in a normal file if I remove this
```json
"injections": {
  "L:source.gts -comment -(string -meta.embedded)": {
    "patterns": [
      {
        "include": "#main"
      }
    ]
  }
},
```

Pulling my hair out.

**Comment by lifeart** [comment]
@evoactivity seems we may compile (ts/js) grammars into gts/gjs indie `md` (but likely grammars should be compile-time resolvable from some source)

**Comment by evoactivity** [comment]
I think we'll need to take an approach similar to svelte where they create different markdown grammars for the different blocks

https://github.com/sveltejs/language-tools/pull/1537/files

I think if we create `markdown-inline-template.json` and have that begin with `<template>` and end with `</template>` we'll be able to inject `inline.template.json` at that point.

I'll look at this later this week though.

**Comment by evoactivity** [comment]
I said later this week but I just tried a hunch and look 😄 

<img width="553" alt="image" src="https://github.com/lifeart/vsc-ember-syntax/assets/83799/9d4a873f-f17a-4ad2-ae44-5cd9f4234ff3">


markdown-gts.json
```json
{
  "fileTypes": [],
  "injectionSelector": "L:text.html.markdown",
  "patterns": [
    {
      "include": "#gts-code-block"
    },
    {
      "name": "meta.js.embeddedTemplateWithoutArgs",
      "begin": "\\s*(<)(template)\\s*(>)",
      "beginCaptures": {
        "1": {
          "name": "punctuation.definition.tag.html"
        },
        "2": {
          "name": "entity.name.tag.other.html"
        },
        "3": {
          "name": "punctuation.definition.tag.html"
        }
      },
      "end": "(</)(template)(>)",
      "endCaptures": {
        "1": {
          "name": "punctuation.definition.tag.html"
        },
        "2": {
          "name": "entity.name.tag.other.html"
        },
        "3": {
          "name": "punctuation.definition.tag.html"
        }
      },
      "patterns": [
        {
          "include": "text.html.ember-handlebars"
        }
      ]
    }
  ],
  "repository": {
    "gts-code-block": {
      "begin": "(^|\\G)(\\s*)(\\`{3,}|~{3,})\\s*(?i:(gts)(\\s+[^`~]*)?$)",
      "name": "markup.fenced_code.block.markdown",
      "end": "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$",
      "beginCaptures": {
        "3": {
          "name": "punctuation.definition.markdown"
        },
        "4": {
          "name": "fenced_code.block.language.markdown"
        },
        "5": {
          "name": "fenced_code.block.language.attributes.markdown"
        }
      },
      "endCaptures": {
        "3": {
          "name": "punctuation.definition.markdown"
        }
      },
      "patterns": [
        {
          "begin": "(^|\\G)(\\s*)(.*)",
          "while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
          "contentName": "meta.embedded.block.gts",
          "patterns": [
            {
              "include": "source.gts"
            }
          ]
        }
      ]
    }
  },
  "scopeName": "markdown.gts.codeblock"
}
```

**Comment by evoactivity** [comment]
I have a path forward to collate all of this into a single `markdown-glimmer.json` that can target both gjs and gts, that I _will_ do later this week.
